<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><title>Contact WS-I - </title><meta name="keywords" content="Web services, interoperability, Basic Profile, Basic Security Profile, Standards, Conformance, UDDI, WSDL, SOAP, XMLSchema" /><meta name="author" content="WS-I Staff" /><link rel="alternate" type="application/rss+xml" title="WS-I RSS Feed" href="/rss/rss-general.xml" /><link type="text/css" rel="stylesheet" href="/css/style.css" media="all" /><link type="text/css" rel="stylesheet" href="/css/print.css" media="print" /><link type="text/css" rel="stylesheet" href="/css/sub.css" media="all" /></head><body><div id="topspace"></div><div id="main"><div id="topnav"><div id="navlinksdiv" ><ul><li><a href="/about/Default.aspx" class="smlnav" accesskey="a">About Us</a></li><li><a href="/deliverables/Default.aspx" accesskey="d">Deliverables</a></li><li><a href="/community/Default.aspx" class="mednav" accesskey="c">Community</a></li><li><a href="/resource/Default.aspx" class="mednav" accesskey="r">Resources</a></li><li><a href="/press/Default.aspx" accesskey="n">News &amp; Events</a></li></ul></div><div class="loginlink" ><a href="http://mp.ws-i.org" target="member" accesskey="l">Member Login</a></div><div class="topsearch" ><div><form method="get" action="/search.aspx"><p><label for="search">Search:</label><input type="text" name="usterms" size="10" maxlength="255" id="search" value="search" accesskey="s" onfocus="if(this.value == 'search'); this.value='';" /></p></form></div></div></div><div id="banner"><a href="/default.aspx"><img src="/images/logo_left.jpg" alt="WS-I Web Services Interoperability Organization" width="183" height="173" /></a><img alt="WSI Banner" width="578" height="174" src="/images/headers/contact_head.jpg"></img></div><a href="#" name="mainblk"></a><div id="leftsect" ><div><ul><li><a href="/contact/Default.aspx" class="bluelink">Contact Us</a></li></ul><div class="smltxt"><img src="/images/find_deliverables.jpg" alt="Find Deliverables" /><br /><table cellpadding="2" cellspacing="0" border="0" style="margin-top:5px;"><tr><td valign="top"><a href="/deliverables/matrix.aspx">View the Matrix</a></td><td align="right"><img src="/images/mini_matrix.gif" border="0" /></td></tr></table></div><div class="smltxt"><img src="/images/comments.jpg" width="164" height="50" alt="What do You Think?" /><br />
          We welcome your feedback on our deliverables<br /><a href="/contact/comment.aspx">Submit a Comment</a></div></div></div><div id="mainsect"><form name="error" method="post" action="pagenotfound.aspx?aspxerrorpath=%2fprofiles%2frsp%2f1.0%2fws-rm%2fdefault.aspx" id="error">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNjAwMjEzNjM0DxYGHgdTZWN0aW9uBQdjb250YWN0HghQYWdlTmFtZQUMcGFnZW5vdGZvdW5kHglQYWdlVGl0bGUFE1dTLUkgUGFnZSBub3QgZm91bmQWAmYPZBYCAgEPDxYCHgRUZXh0BVJUaGUgcGFnZSB5b3UgcmVxdWVzdGVkLDxiPi9wcm9maWxlcy9yc3AvMS4wL3dzLXJtL2RlZmF1bHQuYXNweDwvYj4gZG9lcyBub3QgZXhpc3QuZGRkFBVUt62wdFB7R2uxkOC0YPfC+94=" />
</div>

	<h1>The requested page does not exist on this site</h1>
	<p><span id="errorintro">The page you requested,<b>/profiles/rsp/1.0/ws-rm/default.aspx</b> does not exist.</span></p>
	<h1></h1><p>Recently the WS-I site was revised and the location of some pages was changed. If you requested this url through a link from outside this site, that link may now be outdated.</p><ul><li>For deliverables, including the profiles and testing tools, see the <a href="deliverables/">deliverables</a> section</li><li>For recent news regarding the WS-I activities, see the <a href="press/">news &amp; events</a> section </li><li>To contact WS-I, see the <a href="contact/">contact us</a> section</li><li>The following link returns you to the site's <a href="default.aspx">home page</a></li></ul>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="510B8B35" />
</div></form></div><div id="bottspace" ></div><div id="bottbar" ><ul><li><a href="/contact/Default.aspx">Contact Us</a></li><li><a href="/sitemap.aspx">Site Map</a></li><li><a href="/Docs/Membership/20031104.WS-IPrivacyPolicy.pdf" target="privacy">Privacy Policy</a></li><li class="bottnobrd"><a href="/join/feedbacklicense.aspx">Feedback Policy</a></li><li class="bottnobrd"><a href="/rss/rss-general.xml" target="rss"><img src="/img/rss.gif" alt="RSS" title="RSS" /></a></li></ul><span>© 2009 WS-I, All Rights Reserved | Created by <a href="http://www.pixelmedia.com" target="pixel">PixelMEDIA, Inc.</a></span></div></div></body></html>